title: AARC Learn to Scull Program
description: Training materials for the Ann Arbor Rowing Club's Learn to Scull program
url: https://ilarsf.github.io
baseurl: /aarc_lts
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# Optional settings
show_downloads: false
google_analytics:

# Custom theme settings
theme_color: "#0066cc"         # Primary blue color
theme_color_secondary: "#004c99" # Secondary blue color
footer_text_color: "#7c7c7c"     # Light gray for footer text

# Coach Portal settings
coach_password_hash: 8d783c540a393c2644022d357ef1ef107fb2aad448b991b6fc65634a54078efb
open_sculling_password_hash: 8d783c540a393c2644022d357ef1ef107fb2aad448b991b6fc65634a54078efb # Added for open sculling

# Navigation
navigation:
  - title: Home
    url: /
  - title: For Learners
    url: /for-learners/
    subitems:
      - title: Getting Started
        url: /for-learners/#getting-started
      - title: Learning Journey
        url: /for-learners/#learning-journey
      - title: Technique
        url: /for-learners/#technique
      - title: Safety
        url: /for-learners/#safety
      - title: Resources
        url: /for-learners/#resources
  - title: 🔑 For Coaches
    url: /for-coaches/
  - title: 🔑 Open Sculling
    url: /open-sculling/
  - title: About
    url: /about/
    subitems:
      - title: Meet the Team
        url: /about/team/
      - title: Club Policies
        url: /about/club-policies/
      - title: Contact
        url: /about/contact/
      - title: FAQ
        url: /about/faq/

# Site info
organization: "Ann Arbor Rowing Club"
copyright_year: 2025
