title: AARC Learn to Scull Program
description: Training materials for the Ann Arbor Rowing Club's Learn to Scull program
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# Optional settings
show_downloads: false
google_analytics: 

# Custom theme settings
theme_color: "#0066cc"  # Primary blue color
theme_color_secondary: "#004c99"  # Secondary blue color
footer_text_color: "#7c7c7c"  # Light gray for footer text

# Navigation
navigation:
  - title: Home
    url: /
  - title: Textbook
    url: /textbook/
    subitems:
      - title: "Part 1: Getting Started"
        url: /textbook/chapters/part1.md
      - title: "Part 2: For the Learner"
        url: /textbook/chapters/part2.md
      - title: "Part 3: Safety"
        url: /textbook/chapters/part3.md
      - title: "Part 4: For the Coach"
        url: /textbook/chapters/part4.md
      - title: "Part 5: Appendices"
        url: /textbook/chapters/part5.md
      - title: "View All Chapters"
        url: /textbook/all.md
  - title: Coach Resources
    url: /course_materials/coach/
    subitems:
      - title: Coach Manual
        url: /course_materials/coach/Coach_Manual.html
      - title: Daily Checklist
        url: /course_materials/coach/Daily_Coach_Checklist.html
  - title: Learner Resources
    url: /course_materials/learner/
    subitems:
      - title: Learner Guide
        url: /course_materials/learner/Learner_Guide.html
      - title: Program Schedule
        url: /course_materials/learner/Program_Schedule.html
      - title: Q&A Companion
        url: /course_materials/learner/QA_Companion.html
  - title: Technical Guides
    url: /src/
    subitems:
      - title: Self-Rescue Guide
        url: /src/Sculling_Self_Rescue_Guide.html
      - title: Flip Test Instructions
        url: /src/AARC_Flip_Test_Instructions_20240803.html
      - title: Hand Care Guide
        url: /src/Rowers_Hand_Blister_Treatment.html
  - title: Communication
    url: /course_materials/communication/
  - title: Meet the Team
    url: /team/
  - title: About AARC
    url: /about/
  - title: Resources
    url: /resources/

# Site info
organization: "Ann Arbor Rowing Club"
copyright_year: 2025