title: AARC Learn to Scull Program
description: Training materials for the Ann Arbor Rowing Club's Learn to Scull program
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# Optional settings
show_downloads: false
google_analytics: 

# Custom theme settings
theme_color: "#0066cc"  # Primary blue color
theme_color_secondary: "#004c99"  # Secondary blue color
footer_text_color: "#7c7c7c"  # Light gray for footer text

# Navigation
navigation:
  - title: Home
    url: /
  - title: Coach Resources
    url: /course_materials/coach/
    subitems:
      - title: Coach Manual
        url: /course_materials/coach/Coach_Manual.html
      - title: Daily Checklist
        url: /course_materials/coach/Daily_Coach_Checklist.html
  - title: Learner Resources
    url: /course_materials/learner/
    subitems:
      - title: Learner Guide
        url: /course_materials/learner/Learner_Guide.html
      - title: Q&A Companion
        url: /course_materials/learner/QA_Companion.html
  - title: Technical Guides
    url: /src/
    subitems:
      - title: Self-Rescue Guide
        url: /src/Sculling_Self_Rescue_Guide.html
      - title: Flip Test Instructions
        url: /src/AARC_Flip_Test_Instructions_20240803.html
      - title: Hand Care Guide
        url: /src/Rowers_Hand_Blister_Treatment.html
  - title: Communication
    url: /course_materials/communication/

# Site info
organization: "Ann Arbor Rowing Club"
copyright_year: 2025